### ISSUE TITLE
No config file added when downloading

### ISSUE THREAD

**Issue by notIkibo** [DaFuqs/EnchantmentGroups#4]
I'm on 1.19 2 and I'm searching for the config file to edit?
And how exactly can I turn enchantments to treasure enchantments?

**Comment by notIkibo** [comment]
I guess I took the config file information from the other open issue.

But I have another question: Do I have to put every group innit, else it doesn't work anymore?
What about mods that already have groups. Does it get overwritten?

**Comment by DaFuqs** [comment]
The config file is called `enchantment_groups.json` in your mod config folder.
- You can define enchantments as treasure enchantments by adding their IDs  in the `treasures` list
- All groups that vanilla and other mods define are still active when you remove them from the config. EnchantmentGroups will only add new exclusivities, not override / remove existing ones. The groups in the default config are more like an example on how a finished config file may look (or if you want to add a new protection enchant that should be exclusive to all vanilla protection ones, for example). Feel free to remove all existing entries and add your own :)
