### ISSUE TITLE
Enchantments being hidden, causing it choose wrong enchantment only on server

### ISSUE THREAD

**Issue by GinEverlution** [DaFuqs/EnchantmentGroups#5]
It's a weird one that only present on server

I'm using it with Enhancement, Combat Enchantments and Enchantment Plus, I wanted to make it so that the enchantment Fortune and Looting becomes treasure enchantments. 
This works perfectly normal on single player, but on server, it causes the 2 enchantments to be *hidden*, you can't choose it but it messes the with the ordering of other enchantments by making it so that when you choose one, it will choose the one above it instead.

I know the twos are hidden because I can get them by choosing the enchantment right below the two enchantments before I moved them to treasure enchantments.

**Comment by GinEverlution** [comment]
Choosing Molten and got the one above it
![2023-07-21_01 34 12](https://github.com/DaFuqs/EnchantmentGroups/assets/140104138/bf688052-c655-4606-a10c-de2048355bd6)
![2023-07-21_01 34 21](https://github.com/DaFuqs/EnchantmentGroups/assets/140104138/bf580f51-93a7-4080-92cc-53c598480620)

**Comment by DaFuqs** [comment]
Really weird indeed!
Do both client & server use the same config?

**Comment by GinEverlution** [comment]
Yes I have make sure their config are the same many times and even have just tested it right after seeing your comment.

Works fine on single player but weird on server.

**Comment by DaFuqs** [comment]
Fixed in 1.4.0, see  #7 for reference.
