### ISSUE TITLE
incompatibility not on servers

### ISSUE THREAD

**Issue by dark-enigma** [DaFuqs/EnchantmentGroups#7]
So i am using enchancement:berserk and amarite:accumulate and on survival my config works fine but when i play on servers with it and the config same on the server on quilt 1.19.2 it still lets me combine them

**Comment by DaFuqs** [comment]
I'll look into it.
Via Enchantment Table, Smithing Table, or both?
Any mods that modify how enchanting works?

**Comment by DaFuqs** [comment]
Oh, I think I know what the issue on servers is.

**Comment by DaFuqs** [comment]
The config change in 9d95aeea9e1f63db651e136e23541412925c8f80 introduced a check if an enchantment is in the enchantment registry. But at the point where the config is loaded not all mod initializers have been run yet, so the registry does not contain all modded enchants, still.

I'll get that fixed.

**Comment by DaFuqs** [comment]
What version are you playing on? I've released an updated version for 1.20.1, but I can also do 1.19.2, if needed.

**Comment by kineticV** [comment]
@DaFuqs I'm also having this issue on 1.19.2. I can combine enchantments that are in the same configured enchantment group  using the anvil. This happens in creative and survival. Any chance you could fix this?
