### ISSUE TITLE
1.18.2 config not loaded on servers

### ISSUE THREAD

**Issue by ShiroYatagami** [DaFuqs/EnchantmentGroups#8]
Just loading Enchancement and its dependancies together with EnchantmentGroups on 1.18.2 fabric will result in Enchancement related groups not being loaded properly. I can combine enchantments that I specified in my config regardless of EnchantmentGroup settings.

**Comment by DaFuqs** [comment]
I will look into it, thank you!

**Comment by ConqAra** [comment]
Same issue here!

**Comment by ShiroYatagami** [comment]
Is there any other information you might need or things I could help with to have the problem fixed faster?

**Comment by DaFuqs** [comment]
I will not have access to my dev env until the start of next year, but I will tackle it asap then.

**Comment by ShiroYatagami** [comment]
Sounds good, thanks!

**Comment by DaFuqs** [comment]
I'm testing using the latest EnchantmentGroups and Enchancement + Dependencies on 1.18.2. We are talking https://modrinth.com/mod/enchancement, correct?

Enchancement will only ever allow a single enchant on an item ("Force items to only allow one enchantment"), so I'm kinda curious how you'd even combine enchants in the first place.

**Comment by ShiroYatagami** [comment]
There's a config option to disable that option, "single enchant mode" I believe it's called. That's what I use and am experiencing the issue with.

**Comment by DaFuqs** [comment]
I tried to reproduce your issue, but could not get it to work.
Does that only happen on dedicated servers only?

## Without Enchantment Groups:
![image](https://github.com/DaFuqs/EnchantmentGroups/assets/26429514/47e69e68-0b7a-42db-a8de-444c914734b2)

## With Enchantment Groups:
![image](https://github.com/DaFuqs/EnchantmentGroups/assets/26429514/17bf9b18-b102-4fb9-bd16-8a532f5a75d4)

I used this config:
```json
{
    "test": [
        "enchancement:veil",
        "enchancement:amphibious"
    ]
}
```

**Comment by ShiroYatagami** [comment]
Yeah it only happens on dedicated servers, sorry, I should've mentioned that.
I did make sure to sync the configuration files, and here's mine:
```
{
    "helmet": [
      "enchancement:veil",
      "enchancement:perception",
      "enchancement:assimilation"
    ],
    "chestplate": [
      "enchancement:strafe",
      "enchancement:wardenspine",
      "enchancement:amphibious"
    ],
    "leggings": [
      "enchancement:dash",
      "enchancement:impact",
      "enchancement:slide"
    ],
    "boots": [
      "enchancement:acceleration",
      "enchancement:bouncy",
      "enchancement:gale",
      "enchancement:buoy"
    ],
    "melee": [
      "minecraft:fire_aspect",
      "enchancement:berserk",
      "enchancement:frostbite",
      "soulsweapons:stagger",
      "enchancement:beheading",
      "enchancement:lumberjack",
      "minecraft:silk_touch"
    ],
    "mining": [
      "minecraft:silk_touch",
      "enchancement:extracting",
	  "minecraft:fortune"
    ],
    "shovel": [
      "enchancement:bury",
      "enchancement:scooping"
    ],
    "bow": [
      "minecraft:infinity",
      "enchancement:delay",
      "enchancement:chaos",
      "enchancement:phasing"
    ],
    "trident": [
      "minecraft:channeling",
      "minecraft:riptide",
      "enchancement:leech",
      "enchancement:warp"
    ],
    "crossbow": [
      "minecraft:multishot",
      "minecraft:infinity",
      "enchancement:brimstone",
      "enchancement:homing",
      "enchancement:torch",
      "enchancement:scatter"
    ]
}
```

As well as my Enchancement config:
```
{
  "allowedEnchantments": [
    "enchancement:chaos",
    "enchancement:disarm",
	"minecraft:loyalty"
  ],
  "invertedList": true,
  "overhaulEnchantingTable": false,
  "allowTreasureEnchantmentsInEnchantingTable": false,
  "experienceLevelCost": 5,
  "lapisLazuliCost": 5,
  "singleEnchantmentMode": true,
  "singleLevelMode": false,
  "allowInfinityOnCrossbows": true,
  "allTridentsHaveLoyalty": true,
  "channelingWorksWhenNotThundering": true,
  "fireAspectWorksAsFlintAndSteel": true,
  "freeEnchantedBookMerging": true,
  "luckOfTheSeaHasLure": false,
  "negateEnderPearlDamage": true,
  "safeChanneling": true,
  "tridentsReturnFromVoid": true,
  "weakerPotions": false,
  "weaponEnchantmentCooldownRequirement": 0.7,
  "maxExtractingBlocks": 64,
  "maxLumberjackBlocks": 1024,
  "maxLumberjackHorizontalLength": 7,
  "unbreakingChangesFlag": 0
}
```

I use EnchantmentGroups 1.2.1+1.18.2 and Enchancement 1.18-19.

**Comment by DaFuqs** [comment]
Note from me to me, the Enchancement code back in 1.18:
https://github.com/MoriyaShiine/enchancement/tree/a20391d824e834bd4f4222d2c91977f5579a553b

Boah is that a wack way to manage versions

**Comment by DaFuqs** [comment]
So, I have no idea what the main issue is, but I can easily reproduce it.
Once Enchancement is added, the one mixin Enchantment Groups uses to define it's exclusivities is never being called.

Whatever change on Enchancements side overrides it I cannot tell, sadly. But either way, it will have to be fixed on their side in the first place.
Nothing I can do about that, sorry!
